### ISSUE TITLE
Usage problem

### ISSUE THREAD

**Issue by cacapis** [Nimgoble/WPFTextBoxAutoComplete#5]
Hi, I'm trying but I can't make this work. 
How do I define TestItems? Should it be a new class with a property called TestText?
Thanks a lot.-

> <TextBox 
>        Width="250"
>        HorizontalAlignment="Center"
>        Text="{Binding TestText, UpdateSourceTrigger=PropertyChanged}" 
>        behaviors:AutoCompleteBehavior.AutoCompleteItemsSource="{Binding TestItems}"

**Comment by herurider** [comment]
Oh...I have also same problem...struggling alone with internet for 5 days..
Among many autocomplete codes, I decided to adopt this code because it seems this code matches my project best. 
Mr. Nimbogle would you verykindly please help me to provide simple example which is binding to column of sql database table like (Column Name, Row1 Bill Gates, Row2 Warren Buffet, Row3 Hillary Clinton, Row4 Barrack Obama and so on with many Row(names)) ?
My program will be distributed as 100 % free forever to Korean pharmacies and I'm much sure my program contributes big positiveness to Korean society to be more healthy.
Autocomplete is much different concept of many other data bindings, it's really confusing to understand the role of TestText in autocomplete functioin and Binding to column with many rows of Sql database table.
I installed through Nuget and proceeded only to step 2 of Readme..
I'm not a person of software programming industry and I have used to be salesperson of pharmaceutical industry in Korea, East Asia. Therefore, I've been developing software by learning books alone in Library and feel so sorry to request you this kind of easy example..
Please be the light of mission to our society..

**Comment by Nimgoble** [comment]
Hey @cacapis,

TestText should be a public String property on your DataContext.  
TestItems should be a property that is collection of Strings on your DataContext.

Are you using an MVVM framework?
